algoritmo "DIVISÃO POR ZERO"
// Função :  exibir a mensagem "divisão por zero" caso o divisor = 0
// Autor : Marconys
// Data : 31/01/2022
// Seção de Declarações 
var
a, b: inteiro
inicio
// Digitando o valores de A e B
escreval("Digite o valor de A")
leia(a)
escreval("Digite o valor de b")
leia(b)
se(b <> 0) entao
escreval("O qociente de A / b é:", a \ b)
     senao
     escreval("DIVISÃO POR ZERO")
fimse
fimalgoritmo
