algoritmo "Maior igual"
// Função : verificar qul numero é maior ou se são iguais
// Autor :  Marconys
// Data : 31/01/2022
// Seção de Declarações 
var
a, b: inteiro
inicio
// declarando A e B pelo teclado
escreval("Digite o valor de A")
leia(a)
escreval("Digite o valor de B")
leia(b)
se(a > b) entao
     escreval("A é maior que B")
     senao
     se(a < b) entao
     escreval("B é maior que A")
          senao
          escreval("A é igual a B")
     fimse
fimse
fimalgoritmo
