algoritmo "Metade"
// Função : Mostar a metade quando for maior que cincquenta
// Autor : Marconys
// Data : 21/01/2022
// Seção de Declarações 
var
numero: real
inicio
escreval("Digite um numero")
leia(numero)
se (numero > 50) entao
escreval(" Ametade de", numero, " é: ", numero /2)
senao
se(numero = 50) entao
escreval(numero, " É igual a 50")
senao
escreval(numero, " É menor que 50")
fimse
fimse
fimalgoritmo
